site_name: Rigs of Rods documentation
site_description: Rigs of Rods project documentation
site_author: Rigs of Rods Community
site_url: http://anotherfoxguy.com/ror-docs/

repo_name: RigsOfRods/docs.rigsofrods.org
repo_url: https://github.com/AnotherFoxGuy/ror-docs
edit_uri: blob/master/docs/

copyright: 'Copyright &copy; 2018 Rigs of Rods Community'

theme:
  name: 'material'
  palette:
    primary: 'grey'
    accent: 'orange'