site_name: Rigs of Rods documentation
site_description: Rigs of Rods project documentation
site_author: Rigs of Rods Community
site_url: http://docs.rigsofrods.org

repo_name: RigsOfRods/docs.rigsofrods.org
repo_url: https://github.com/RigsOfRods/docs.rigsofrods.org
edit_uri: master/docs/

copyright: 'Copyright &copy; 2018 Rigs of Rods Community'

theme:
  name: 'material'

extra_css:
  - 'stylesheets/extra.css'
