site_name: Rigs of Rods documentation
site_description: Rigs of Rods project documentation
site_author: Rigs of Rods Community
site_url: https://rigsofrods.cf/

docs_dir: source

repo_name: AnotherFoxGuy/ror-docs
repo_url: https://github.com/AnotherFoxGuy/ror-docs
edit_uri: blob/master/docs/

copyright: 'Copyright &copy; 2018 Rigs of Rods Community'

theme:
  name: 'material'
  palette:
    primary: 'blue'
    accent: 'orange'
